# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x43ommon.proto\x12\x18serosystems.proto.v3.grx\"[\n\x13RadioIdentification\x12,\n\x04\x62\x61nd\x18\x01 \x01(\x0e\x32\x1e.serosystems.proto.v3.grx.Band\x12\x16\n\x0eper_band_index\x18\x02 \x01(\x05*\x8c\x01\n\x04\x42\x61nd\x12\x14\n\x10\x42\x41ND_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x42\x41ND_978_MHZ\x10\x01\x12\x11\n\rBAND_1030_MHZ\x10\x02\x12\x11\n\rBAND_1090_MHZ\x10\x03\x12\x0e\n\nBAND_FIXED\x10\x7f\x12\x11\n\x0c\x42\x41ND_TUNABLE\x10\x80\x01\x12\x13\n\x0e\x42\x41ND_MATCH_ANY\x10\xfe\x01\x42*\n\x1b\x64\x65.serosystems.proto.v3.grxB\x0b\x43ommonProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033de.serosystems.proto.v3.grxB\013CommonProto'
  _BAND._serialized_start=136
  _BAND._serialized_end=276
  _RADIOIDENTIFICATION._serialized_start=42
  _RADIOIDENTIFICATION._serialized_end=133
# @@protoc_insertion_point(module_scope)
