# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import Monitord_pb2 as Monitord__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class MonitordStub(object):
    """Monitor daemon service definition. Port 5305. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCPUUsage = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetCPUUsage',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.CPUUsage.FromString,
                )
        self.GetCPUUsageHistory = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetCPUUsageHistory',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetCPUUsageHistoryReply.FromString,
                )
        self.GetMemoryUsage = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetMemoryUsage',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.MemoryUsage.FromString,
                )
        self.GetMemoryUsageHistory = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetMemoryUsageHistory',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetMemoryUsageHistoryReply.FromString,
                )
        self.GetSwapUsage = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetSwapUsage',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.SwapUsage.FromString,
                )
        self.GetSwapUsageHistory = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetSwapUsageHistory',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetSwapUsageHistoryReply.FromString,
                )
        self.GetMountedFilesystemUsage = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetMountedFilesystemUsage',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetMountedFilesystemUsageReply.FromString,
                )
        self.GetProcessList = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetProcessList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetProcessListReply.FromString,
                )
        self.GetSystemPackages = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemPackages',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetSystemPackagesReply.FromString,
                )
        self.GetLogMessages = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetLogMessages',
                request_serializer=Monitord__pb2.GetLogMessagesRequest.SerializeToString,
                response_deserializer=Monitord__pb2.GetLogMessagesReply.FromString,
                )
        self.GetUnitList = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetUnitList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetUnitListReply.FromString,
                )
        self.GetNetworkUsage = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetNetworkUsage',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetNetworkUsageReply.FromString,
                )
        self.GetNetworkUsageHistory = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetNetworkUsageHistory',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetNetworkUsageHistoryReply.FromString,
                )
        self.GetNetworkCounters = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetNetworkCounters',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetNetworkCountersReply.FromString,
                )
        self.GetSystemHealth = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemHealth',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.SystemHealth.FromString,
                )
        self.GetSystemHealthHistory = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemHealthHistory',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetSystemHealthHistoryReply.FromString,
                )
        self.GetSystemLoad = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemLoad',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.SystemLoad.FromString,
                )
        self.GetSystemLoadHistory = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemLoadHistory',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetSystemLoadHistoryReply.FromString,
                )
        self.GetSystemInformation = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemInformation',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.SystemInformation.FromString,
                )
        self.ClearResetReasons = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/ClearResetReasons',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetGNSSInformation = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetGNSSInformation',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GNSSInformation.FromString,
                )
        self.GetFullSystemStatus = channel.unary_unary(
                '/serosystems.proto.v3.grx.monitord.Monitord/GetFullSystemStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Monitord__pb2.GetFullSystemStatusReply.FromString,
                )


class MonitordServicer(object):
    """Monitor daemon service definition. Port 5305. 
    """

    def GetCPUUsage(self, request, context):
        """Get current CPU usage. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCPUUsageHistory(self, request, context):
        """Get history of CPU usage. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryUsage(self, request, context):
        """Get current memory usage. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryUsageHistory(self, request, context):
        """Get history of memory usage. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSwapUsage(self, request, context):
        """Get current swap usage. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSwapUsageHistory(self, request, context):
        """Get history of swap usage. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMountedFilesystemUsage(self, request, context):
        """Get current file system usage. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessList(self, request, context):
        """Get a list of processes. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemPackages(self, request, context):
        """Get a list of (installed) system packages. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogMessages(self, request, context):
        """Get log messages (without streaming/waiting for new ones). 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnitList(self, request, context):
        """Get a list (with states) of systemd units. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworkUsage(self, request, context):
        """Get current network usage. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworkUsageHistory(self, request, context):
        """Get history of network usage. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworkCounters(self, request, context):
        """Get counters (in contrast to the rates) of the network usage. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemHealth(self, request, context):
        """Get current system health. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemHealthHistory(self, request, context):
        """Get history of system health. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemLoad(self, request, context):
        """Get current system load. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemLoadHistory(self, request, context):
        """Get history of system load. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemInformation(self, request, context):
        """
        Get (lower level) information about the system, like e.g. uptime, reset
        reasons or low-level version information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearResetReasons(self, request, context):
        """
        Clear all reset resons (see SystemInformation message).
        This can be used to "acknowledge" certain events, such as a watchdog reset
        (or also a simple "power on reset").
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGNSSInformation(self, request, context):
        """
        Get information related to the Global Navigation Satellite System
        (GNSS).
        Note: if the information is not available or outdated, the gRPC
        call will fail with status code ABORTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullSystemStatus(self, request, context):
        """Get full system status (single call for 7 most used calls).
        Note: submessages may be omitted if the "sub calls" fail, e.g.
        if GNSS information are invalid, the `gnss_information` submessage
        will not be included.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitordServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCPUUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCPUUsage,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.CPUUsage.SerializeToString,
            ),
            'GetCPUUsageHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCPUUsageHistory,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetCPUUsageHistoryReply.SerializeToString,
            ),
            'GetMemoryUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryUsage,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.MemoryUsage.SerializeToString,
            ),
            'GetMemoryUsageHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryUsageHistory,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetMemoryUsageHistoryReply.SerializeToString,
            ),
            'GetSwapUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSwapUsage,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.SwapUsage.SerializeToString,
            ),
            'GetSwapUsageHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSwapUsageHistory,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetSwapUsageHistoryReply.SerializeToString,
            ),
            'GetMountedFilesystemUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMountedFilesystemUsage,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetMountedFilesystemUsageReply.SerializeToString,
            ),
            'GetProcessList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetProcessListReply.SerializeToString,
            ),
            'GetSystemPackages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemPackages,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetSystemPackagesReply.SerializeToString,
            ),
            'GetLogMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogMessages,
                    request_deserializer=Monitord__pb2.GetLogMessagesRequest.FromString,
                    response_serializer=Monitord__pb2.GetLogMessagesReply.SerializeToString,
            ),
            'GetUnitList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnitList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetUnitListReply.SerializeToString,
            ),
            'GetNetworkUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkUsage,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetNetworkUsageReply.SerializeToString,
            ),
            'GetNetworkUsageHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkUsageHistory,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetNetworkUsageHistoryReply.SerializeToString,
            ),
            'GetNetworkCounters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkCounters,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetNetworkCountersReply.SerializeToString,
            ),
            'GetSystemHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemHealth,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.SystemHealth.SerializeToString,
            ),
            'GetSystemHealthHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemHealthHistory,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetSystemHealthHistoryReply.SerializeToString,
            ),
            'GetSystemLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemLoad,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.SystemLoad.SerializeToString,
            ),
            'GetSystemLoadHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemLoadHistory,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetSystemLoadHistoryReply.SerializeToString,
            ),
            'GetSystemInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemInformation,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.SystemInformation.SerializeToString,
            ),
            'ClearResetReasons': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearResetReasons,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetGNSSInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGNSSInformation,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GNSSInformation.SerializeToString,
            ),
            'GetFullSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullSystemStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Monitord__pb2.GetFullSystemStatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serosystems.proto.v3.grx.monitord.Monitord', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Monitord(object):
    """Monitor daemon service definition. Port 5305. 
    """

    @staticmethod
    def GetCPUUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetCPUUsage',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.CPUUsage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCPUUsageHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetCPUUsageHistory',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetCPUUsageHistoryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMemoryUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetMemoryUsage',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.MemoryUsage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMemoryUsageHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetMemoryUsageHistory',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetMemoryUsageHistoryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSwapUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetSwapUsage',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.SwapUsage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSwapUsageHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetSwapUsageHistory',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetSwapUsageHistoryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMountedFilesystemUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetMountedFilesystemUsage',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetMountedFilesystemUsageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProcessList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetProcessList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetProcessListReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemPackages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemPackages',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetSystemPackagesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLogMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetLogMessages',
            Monitord__pb2.GetLogMessagesRequest.SerializeToString,
            Monitord__pb2.GetLogMessagesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUnitList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetUnitList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetUnitListReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetworkUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetNetworkUsage',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetNetworkUsageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetworkUsageHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetNetworkUsageHistory',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetNetworkUsageHistoryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetworkCounters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetNetworkCounters',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetNetworkCountersReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemHealth',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.SystemHealth.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemHealthHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemHealthHistory',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetSystemHealthHistoryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemLoad',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.SystemLoad.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemLoadHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemLoadHistory',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetSystemLoadHistoryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetSystemInformation',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.SystemInformation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearResetReasons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/ClearResetReasons',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGNSSInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetGNSSInformation',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GNSSInformation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFullSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.monitord.Monitord/GetFullSystemStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Monitord__pb2.GetFullSystemStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
