# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import Receiverd_pb2 as Receiverd__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ReceiverdStub(object):
    """Receiver daemon service definition. Port 5303. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStateVectors = channel.unary_unary(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetStateVectors',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Receiverd__pb2.StateVectorList.FromString,
                )
        self.GetStateVectorHistory = channel.unary_unary(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetStateVectorHistory',
                request_serializer=Receiverd__pb2.GetStateVectorHistoryRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.StateVectorHistory.FromString,
                )
        self.GetRangeChart = channel.unary_unary(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetRangeChart',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Receiverd__pb2.RangeChart.FromString,
                )
        self.ResetRangeChart = channel.unary_unary(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/ResetRangeChart',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetStatistics = channel.unary_unary(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetStatistics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Receiverd__pb2.Statistics.FromString,
                )
        self.GetSamplesStatistics = channel.unary_unary(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetSamplesStatistics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Receiverd__pb2.SamplesStatistics.FromString,
                )
        self.GetRadioFrontEndStatus = channel.unary_unary(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetRadioFrontEndStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Receiverd__pb2.GetRadioFrontEndStatusReply.FromString,
                )
        self.RecalibrateDCOffset = channel.unary_unary(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/RecalibrateDCOffset',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetModeSDownlinkFrames = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetModeSDownlinkFrames',
                request_serializer=Receiverd__pb2.GetModeSDownlinkFramesRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.ModeSDownlinkFrameWithStreamInfo.FromString,
                )
        self.GetModeSUplinkFrames = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetModeSUplinkFrames',
                request_serializer=Receiverd__pb2.GetModeSUplinkFramesRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.ModeSUplinkFrameWithStreamInfo.FromString,
                )
        self.GetModeACDownlinkFrames = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetModeACDownlinkFrames',
                request_serializer=Receiverd__pb2.GetModeACDownlinkFramesRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.ModeACDownlinkBinnedFrameWithStreamInfo.FromString,
                )
        self.GetUATADSBMessages = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetUATADSBMessages',
                request_serializer=Receiverd__pb2.GetUATADSBMessagesRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.UATADSBMessageWithStreamInfo.FromString,
                )
        self.GetUATGroundUplinkMessages = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetUATGroundUplinkMessages',
                request_serializer=Receiverd__pb2.GetUATGroundUplinkMessagesRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.UATGroundUplinkMessageWithStreamInfo.FromString,
                )
        self.GetDMETACANPulsePairs = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetDMETACANPulsePairs',
                request_serializer=Receiverd__pb2.GetDMETACANPulsePairsRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.DMETACANPulsePairWithStreamInfo.FromString,
                )
        self.GetIsolatedPulses = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetIsolatedPulses',
                request_serializer=Receiverd__pb2.GetIsolatedPulsesRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.IsolatedPulseWithStreamInfo.FromString,
                )
        self.GetMode4Interrogations = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetMode4Interrogations',
                request_serializer=Receiverd__pb2.GetMode4InterrogationsRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.Mode4InterrogationWithStreamInfo.FromString,
                )
        self.GetMode4Replies = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetMode4Replies',
                request_serializer=Receiverd__pb2.GetMode4RepliesRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.Mode4ReplyWithStreamInfo.FromString,
                )
        self.GetMode5Interrogations = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetMode5Interrogations',
                request_serializer=Receiverd__pb2.GetMode5InterrogationsRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.Mode5InterrogationWithStreamInfo.FromString,
                )
        self.GetMode5Replies = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetMode5Replies',
                request_serializer=Receiverd__pb2.GetMode5RepliesRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.Mode5ReplyWithStreamInfo.FromString,
                )
        self.GetMode123ACInterrogations = channel.unary_stream(
                '/serosystems.proto.v3.grx.receiverd.Receiverd/GetMode123ACInterrogations',
                request_serializer=Receiverd__pb2.GetMode123ACInterrogationsRequest.SerializeToString,
                response_deserializer=Receiverd__pb2.Mode123ACInterrogationWithStreamInfo.FromString,
                )


class ReceiverdServicer(object):
    """Receiver daemon service definition. Port 5303. 
    """

    def GetStateVectors(self, request, context):
        """
        Get a list of state vectors.
        Returns UNAVAILABLE if receiverd could not be reached.
        Returns DEADLINE_UNAVAILABLE if receiverd did not reply in time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateVectorHistory(self, request, context):
        """
        Get a history of state vectors for some target.
        Returns UNAVAILABLE if receiverd could not be reached.
        Returns DEADLINE_UNAVAILABLE if receiverd did not reply in time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRangeChart(self, request, context):
        """
        Get a range chart.
        Returns UNAVAILABLE if receiverd could not be reached.
        Returns DEADLINE_UNAVAILABLE if receiverd did not reply in time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetRangeChart(self, request, context):
        """
        Reset range chart.
        Returns UNAVAILABLE if receiverd could not be reached.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatistics(self, request, context):
        """
        Get received signal counters and rates.
        Returns UNAVAILABLE if receiverd could not be reached.
        Returns DEADLINE_UNAVAILABLE if receiverd did not reply in time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSamplesStatistics(self, request, context):
        """
        Get samples statistics.
        Returns UNAVAILABLE if receiverd could not be reached.
        Returns DEADLINE_UNAVAILABLE if receiverd did not reply in time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRadioFrontEndStatus(self, request, context):
        """
        Get radio frontend status.
        Returns UNAVAILABLE if receiverd could not be reached.
        Returns DEADLINE_UNAVAILABLE if receiverd did not reply in time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecalibrateDCOffset(self, request, context):
        """
        Recalibrate DC offset.
        Should be done if
        rf.dc_offset_calibration_recalibration_advised or
        rf.dc_offset_calibration_recalibration_required
        for some rf as returned by GetRadioFrontEndStatus() is set.
        Ongoing calibration can be monitored by
        rf.dc_offset_calibration_ongoing, see also
        documentation on the fields in RadioFrontEndStatus.
        Returns UNAVAILABLE if receiverd could not be reached.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModeSDownlinkFrames(self, request, context):
        """
        Request a stream of Mode S downlink frames (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetModeSDownlinkFramesRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModeSUplinkFrames(self, request, context):
        """
        Request a stream of Mode S uplink frames (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetModeSUplinkFramesRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModeACDownlinkFrames(self, request, context):
        """
        Request a stream of Mode AC downlink frames (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetModeACDownlinkFramesRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUATADSBMessages(self, request, context):
        """
        Request a stream of UAT ADS-B messages (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetModeSDownlinkFramesRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUATGroundUplinkMessages(self, request, context):
        """
        Request a stream of UAT Ground Uplink messages (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetModeSDownlinkFramesRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDMETACANPulsePairs(self, request, context):
        """
        Request a stream of DME/TACAN pulse pairs (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetDMETACANPulsePairsRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIsolatedPulses(self, request, context):
        """
        Request a stream of isolated pulses (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetIsolatedPulsesRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMode4Interrogations(self, request, context):
        """
        Request a stream of Mode 4 Interrogations (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetMode4InterrogationsRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMode4Replies(self, request, context):
        """
        Request a stream of Mode 4 Replies (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetMode4RepliesRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMode5Interrogations(self, request, context):
        """
        Request a stream of Mode 5 Interrogations (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetMode5InterrogationsRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMode5Replies(self, request, context):
        """
        Request a stream of Mode 5 Replies (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetMode5RepliesRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMode123ACInterrogations(self, request, context):
        """
        Request a stream of Mode123ACInterrogations (matching the request) from
        the server.
        For reconfiguration, the call has to be cancelled.
        Returns UNAVAILABLE if the service is shutting down.
        Returns INVALID_ARGUMENT if request was invalid, see GetMode123ACInterrogationsRequest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiverdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStateVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateVectors,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Receiverd__pb2.StateVectorList.SerializeToString,
            ),
            'GetStateVectorHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateVectorHistory,
                    request_deserializer=Receiverd__pb2.GetStateVectorHistoryRequest.FromString,
                    response_serializer=Receiverd__pb2.StateVectorHistory.SerializeToString,
            ),
            'GetRangeChart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRangeChart,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Receiverd__pb2.RangeChart.SerializeToString,
            ),
            'ResetRangeChart': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetRangeChart,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatistics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Receiverd__pb2.Statistics.SerializeToString,
            ),
            'GetSamplesStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSamplesStatistics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Receiverd__pb2.SamplesStatistics.SerializeToString,
            ),
            'GetRadioFrontEndStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRadioFrontEndStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Receiverd__pb2.GetRadioFrontEndStatusReply.SerializeToString,
            ),
            'RecalibrateDCOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.RecalibrateDCOffset,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetModeSDownlinkFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.GetModeSDownlinkFrames,
                    request_deserializer=Receiverd__pb2.GetModeSDownlinkFramesRequest.FromString,
                    response_serializer=Receiverd__pb2.ModeSDownlinkFrameWithStreamInfo.SerializeToString,
            ),
            'GetModeSUplinkFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.GetModeSUplinkFrames,
                    request_deserializer=Receiverd__pb2.GetModeSUplinkFramesRequest.FromString,
                    response_serializer=Receiverd__pb2.ModeSUplinkFrameWithStreamInfo.SerializeToString,
            ),
            'GetModeACDownlinkFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.GetModeACDownlinkFrames,
                    request_deserializer=Receiverd__pb2.GetModeACDownlinkFramesRequest.FromString,
                    response_serializer=Receiverd__pb2.ModeACDownlinkBinnedFrameWithStreamInfo.SerializeToString,
            ),
            'GetUATADSBMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUATADSBMessages,
                    request_deserializer=Receiverd__pb2.GetUATADSBMessagesRequest.FromString,
                    response_serializer=Receiverd__pb2.UATADSBMessageWithStreamInfo.SerializeToString,
            ),
            'GetUATGroundUplinkMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUATGroundUplinkMessages,
                    request_deserializer=Receiverd__pb2.GetUATGroundUplinkMessagesRequest.FromString,
                    response_serializer=Receiverd__pb2.UATGroundUplinkMessageWithStreamInfo.SerializeToString,
            ),
            'GetDMETACANPulsePairs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetDMETACANPulsePairs,
                    request_deserializer=Receiverd__pb2.GetDMETACANPulsePairsRequest.FromString,
                    response_serializer=Receiverd__pb2.DMETACANPulsePairWithStreamInfo.SerializeToString,
            ),
            'GetIsolatedPulses': grpc.unary_stream_rpc_method_handler(
                    servicer.GetIsolatedPulses,
                    request_deserializer=Receiverd__pb2.GetIsolatedPulsesRequest.FromString,
                    response_serializer=Receiverd__pb2.IsolatedPulseWithStreamInfo.SerializeToString,
            ),
            'GetMode4Interrogations': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMode4Interrogations,
                    request_deserializer=Receiverd__pb2.GetMode4InterrogationsRequest.FromString,
                    response_serializer=Receiverd__pb2.Mode4InterrogationWithStreamInfo.SerializeToString,
            ),
            'GetMode4Replies': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMode4Replies,
                    request_deserializer=Receiverd__pb2.GetMode4RepliesRequest.FromString,
                    response_serializer=Receiverd__pb2.Mode4ReplyWithStreamInfo.SerializeToString,
            ),
            'GetMode5Interrogations': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMode5Interrogations,
                    request_deserializer=Receiverd__pb2.GetMode5InterrogationsRequest.FromString,
                    response_serializer=Receiverd__pb2.Mode5InterrogationWithStreamInfo.SerializeToString,
            ),
            'GetMode5Replies': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMode5Replies,
                    request_deserializer=Receiverd__pb2.GetMode5RepliesRequest.FromString,
                    response_serializer=Receiverd__pb2.Mode5ReplyWithStreamInfo.SerializeToString,
            ),
            'GetMode123ACInterrogations': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMode123ACInterrogations,
                    request_deserializer=Receiverd__pb2.GetMode123ACInterrogationsRequest.FromString,
                    response_serializer=Receiverd__pb2.Mode123ACInterrogationWithStreamInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serosystems.proto.v3.grx.receiverd.Receiverd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Receiverd(object):
    """Receiver daemon service definition. Port 5303. 
    """

    @staticmethod
    def GetStateVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetStateVectors',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Receiverd__pb2.StateVectorList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStateVectorHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetStateVectorHistory',
            Receiverd__pb2.GetStateVectorHistoryRequest.SerializeToString,
            Receiverd__pb2.StateVectorHistory.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRangeChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetRangeChart',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Receiverd__pb2.RangeChart.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetRangeChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/ResetRangeChart',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetStatistics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Receiverd__pb2.Statistics.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSamplesStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetSamplesStatistics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Receiverd__pb2.SamplesStatistics.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRadioFrontEndStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetRadioFrontEndStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Receiverd__pb2.GetRadioFrontEndStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecalibrateDCOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/RecalibrateDCOffset',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModeSDownlinkFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetModeSDownlinkFrames',
            Receiverd__pb2.GetModeSDownlinkFramesRequest.SerializeToString,
            Receiverd__pb2.ModeSDownlinkFrameWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModeSUplinkFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetModeSUplinkFrames',
            Receiverd__pb2.GetModeSUplinkFramesRequest.SerializeToString,
            Receiverd__pb2.ModeSUplinkFrameWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModeACDownlinkFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetModeACDownlinkFrames',
            Receiverd__pb2.GetModeACDownlinkFramesRequest.SerializeToString,
            Receiverd__pb2.ModeACDownlinkBinnedFrameWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUATADSBMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetUATADSBMessages',
            Receiverd__pb2.GetUATADSBMessagesRequest.SerializeToString,
            Receiverd__pb2.UATADSBMessageWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUATGroundUplinkMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetUATGroundUplinkMessages',
            Receiverd__pb2.GetUATGroundUplinkMessagesRequest.SerializeToString,
            Receiverd__pb2.UATGroundUplinkMessageWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDMETACANPulsePairs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetDMETACANPulsePairs',
            Receiverd__pb2.GetDMETACANPulsePairsRequest.SerializeToString,
            Receiverd__pb2.DMETACANPulsePairWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIsolatedPulses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetIsolatedPulses',
            Receiverd__pb2.GetIsolatedPulsesRequest.SerializeToString,
            Receiverd__pb2.IsolatedPulseWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMode4Interrogations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetMode4Interrogations',
            Receiverd__pb2.GetMode4InterrogationsRequest.SerializeToString,
            Receiverd__pb2.Mode4InterrogationWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMode4Replies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetMode4Replies',
            Receiverd__pb2.GetMode4RepliesRequest.SerializeToString,
            Receiverd__pb2.Mode4ReplyWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMode5Interrogations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetMode5Interrogations',
            Receiverd__pb2.GetMode5InterrogationsRequest.SerializeToString,
            Receiverd__pb2.Mode5InterrogationWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMode5Replies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetMode5Replies',
            Receiverd__pb2.GetMode5RepliesRequest.SerializeToString,
            Receiverd__pb2.Mode5ReplyWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMode123ACInterrogations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.receiverd.Receiverd/GetMode123ACInterrogations',
            Receiverd__pb2.GetMode123ACInterrogationsRequest.SerializeToString,
            Receiverd__pb2.Mode123ACInterrogationWithStreamInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
