# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import Samplestreamingd_pb2 as Samplestreamingd__pb2


class SamplestreamingdStub(object):
    """Sample streaming daemon service definition. Port 5308. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStreamProperties = channel.unary_unary(
                '/serosystems.proto.v3.grx.samplestreamingd.Samplestreamingd/GetStreamProperties',
                request_serializer=Samplestreamingd__pb2.GetStreamPropertiesRequest.SerializeToString,
                response_deserializer=Samplestreamingd__pb2.StreamProperties.FromString,
                )
        self.StartStream = channel.unary_stream(
                '/serosystems.proto.v3.grx.samplestreamingd.Samplestreamingd/StartStream',
                request_serializer=Samplestreamingd__pb2.StartStreamRequest.SerializeToString,
                response_deserializer=Samplestreamingd__pb2.StartStreamReply.FromString,
                )


class SamplestreamingdServicer(object):
    """Sample streaming daemon service definition. Port 5308. 
    """

    def GetStreamProperties(self, request, context):
        """Request the stream properties. They usually do not change over time
        (unless the radio front-end allows retuning/changing settings, see TunableChanneld).
        Returns INVALID_ARGUMENT if chosen RX channel is not available.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStream(self, request, context):
        """
        Request a stream of samples.
        Returns INVALID_ARGUMENT if chosen RX channel is not available
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SamplestreamingdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStreamProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamProperties,
                    request_deserializer=Samplestreamingd__pb2.GetStreamPropertiesRequest.FromString,
                    response_serializer=Samplestreamingd__pb2.StreamProperties.SerializeToString,
            ),
            'StartStream': grpc.unary_stream_rpc_method_handler(
                    servicer.StartStream,
                    request_deserializer=Samplestreamingd__pb2.StartStreamRequest.FromString,
                    response_serializer=Samplestreamingd__pb2.StartStreamReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serosystems.proto.v3.grx.samplestreamingd.Samplestreamingd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Samplestreamingd(object):
    """Sample streaming daemon service definition. Port 5308. 
    """

    @staticmethod
    def GetStreamProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.samplestreamingd.Samplestreamingd/GetStreamProperties',
            Samplestreamingd__pb2.GetStreamPropertiesRequest.SerializeToString,
            Samplestreamingd__pb2.StreamProperties.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/serosystems.proto.v3.grx.samplestreamingd.Samplestreamingd/StartStream',
            Samplestreamingd__pb2.StartStreamRequest.SerializeToString,
            Samplestreamingd__pb2.StartStreamReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
