# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Samplestreamingd.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16Samplestreamingd.proto\x12)serosystems.proto.v3.grx.samplestreamingd\x1a\x0c\x43ommon.proto\"\\\n\x10StreamProperties\x12\x18\n\x10\x63\x65nter_frequency\x18\x01 \x01(\r\x12\x13\n\x0bsample_rate\x18\x02 \x01(\r\x12\x19\n\x11\x63\x61libration_value\x18\x03 \x01(\x02\"i\n\x1aGetStreamPropertiesRequest\x12K\n\x14radio_identification\x18\x01 \x01(\x0b\x32-.serosystems.proto.v3.grx.RadioIdentification\"{\n\x12StartStreamRequest\x12K\n\x14radio_identification\x18\x01 \x01(\x0b\x32-.serosystems.proto.v3.grx.RadioIdentification\x12\x18\n\x10requested_blocks\x18\x02 \x01(\r\"Q\n\x10StartStreamReply\x12\x17\n\x0f\x62lock_timestamp\x18\x01 \x01(\x04\x12\x0f\n\x07samples\x18\x02 \x01(\x0c\x12\x13\n\x0blost_blocks\x18\x03 \x01(\r2\xbe\x02\n\x10Samplestreamingd\x12\x99\x01\n\x13GetStreamProperties\x12\x45.serosystems.proto.v3.grx.samplestreamingd.GetStreamPropertiesRequest\x1a;.serosystems.proto.v3.grx.samplestreamingd.StreamProperties\x12\x8d\x01\n\x0bStartStream\x12=.serosystems.proto.v3.grx.samplestreamingd.StartStreamRequest\x1a;.serosystems.proto.v3.grx.samplestreamingd.StartStreamReply\"\x00\x30\x01\x42\x45\n,de.serosystems.proto.v3.grx.samplestreamingdB\x15SamplestreamingDProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Samplestreamingd_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n,de.serosystems.proto.v3.grx.samplestreamingdB\025SamplestreamingDProto'
  _STREAMPROPERTIES._serialized_start=83
  _STREAMPROPERTIES._serialized_end=175
  _GETSTREAMPROPERTIESREQUEST._serialized_start=177
  _GETSTREAMPROPERTIESREQUEST._serialized_end=282
  _STARTSTREAMREQUEST._serialized_start=284
  _STARTSTREAMREQUEST._serialized_end=407
  _STARTSTREAMREPLY._serialized_start=409
  _STARTSTREAMREPLY._serialized_end=490
  _SAMPLESTREAMINGD._serialized_start=493
  _SAMPLESTREAMINGD._serialized_end=811
# @@protoc_insertion_point(module_scope)
