# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import TunableChanneld_pb2 as TunableChanneld__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class TunableChanneldStub(object):
    """TunableChannel daemon service definition. Port 5309. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChannels = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetChannels',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=TunableChanneld__pb2.GetChannelsReply.FromString,
                )
        self.GetRXPorts = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetRXPorts',
                request_serializer=TunableChanneld__pb2.GetRXPortsRequest.SerializeToString,
                response_deserializer=TunableChanneld__pb2.GetRXPortsReply.FromString,
                )
        self.GetRXPort = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetRXPort',
                request_serializer=TunableChanneld__pb2.GetRXPortRequest.SerializeToString,
                response_deserializer=TunableChanneld__pb2.GetRXPortReply.FromString,
                )
        self.SetRXPort = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/SetRXPort',
                request_serializer=TunableChanneld__pb2.SetRXPortRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetCenterFrequency = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetCenterFrequency',
                request_serializer=TunableChanneld__pb2.GetCenterFrequencyRequest.SerializeToString,
                response_deserializer=TunableChanneld__pb2.GetCenterFrequencyReply.FromString,
                )
        self.SetCenterFrequency = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/SetCenterFrequency',
                request_serializer=TunableChanneld__pb2.SetCenterFrequencyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetAnalogBandwidth = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetAnalogBandwidth',
                request_serializer=TunableChanneld__pb2.GetAnalogBandwidthRequest.SerializeToString,
                response_deserializer=TunableChanneld__pb2.GetAnalogBandwidthReply.FromString,
                )
        self.SetAnalogBandwidth = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/SetAnalogBandwidth',
                request_serializer=TunableChanneld__pb2.SetAnalogBandwidthRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetSampleRate = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetSampleRate',
                request_serializer=TunableChanneld__pb2.GetSampleRateRequest.SerializeToString,
                response_deserializer=TunableChanneld__pb2.GetSampleRateReply.FromString,
                )
        self.SetSampleRate = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/SetSampleRate',
                request_serializer=TunableChanneld__pb2.SetSampleRateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetHardwareGain = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetHardwareGain',
                request_serializer=TunableChanneld__pb2.GetHardwareGainRequest.SerializeToString,
                response_deserializer=TunableChanneld__pb2.GetHardwareGainReply.FromString,
                )
        self.SetHardwareGain = channel.unary_unary(
                '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/SetHardwareGain',
                request_serializer=TunableChanneld__pb2.SetHardwareGainRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class TunableChanneldServicer(object):
    """TunableChannel daemon service definition. Port 5309. 
    """

    def GetChannels(self, request, context):
        """Get a list of all (tunable) channels 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRXPorts(self, request, context):
        """Get a list of RX ports of the specified channel
        Returns INVALID_ARGUMENT if request was invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRXPort(self, request, context):
        """Get the currently chosen RX port of the specified channel
        Returns INVALID_ARGUMENT if request was invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRXPort(self, request, context):
        """Choose the RX port of the specified channel
        Returns INVALID_ARGUMENT if request was invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCenterFrequency(self, request, context):
        """Get the center frequency [Hz] of the specified channel.
        Returns INVALID_ARGUMENT if request was invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCenterFrequency(self, request, context):
        """Set the center frequency [Hz] of the specified channel.
        Returns INVALID_ARGUMENT if request was invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalogBandwidth(self, request, context):
        """Get the analog bandwidth [Hz] of the specified channel.
        Returns INVALID_ARGUMENT if request was invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAnalogBandwidth(self, request, context):
        """Set the analog bandwidth [Hz] of the specified channel.
        Returns INVALID_ARGUMENT if request was invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSampleRate(self, request, context):
        """Get the sample rate [Sps] of the specified channel.
        Returns INVALID_ARGUMENT if request was invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSampleRate(self, request, context):
        """Set the sample rate [Sps] of the specified channel.
        WARNING: changing the sample rate may interrupt the sampling process/data flow for a while

        Returns INVALID_ARGUMENT if request was invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHardwareGain(self, request, context):
        """Get the hardware gain [dB] of the specified channel.
        Returns INVALID_ARGUMENT if request was invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetHardwareGain(self, request, context):
        """Set the hardware gain [dB] of the specified channel.
        Returns INVALID_ARGUMENT if request was invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TunableChanneldServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannels,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=TunableChanneld__pb2.GetChannelsReply.SerializeToString,
            ),
            'GetRXPorts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRXPorts,
                    request_deserializer=TunableChanneld__pb2.GetRXPortsRequest.FromString,
                    response_serializer=TunableChanneld__pb2.GetRXPortsReply.SerializeToString,
            ),
            'GetRXPort': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRXPort,
                    request_deserializer=TunableChanneld__pb2.GetRXPortRequest.FromString,
                    response_serializer=TunableChanneld__pb2.GetRXPortReply.SerializeToString,
            ),
            'SetRXPort': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRXPort,
                    request_deserializer=TunableChanneld__pb2.SetRXPortRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCenterFrequency': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCenterFrequency,
                    request_deserializer=TunableChanneld__pb2.GetCenterFrequencyRequest.FromString,
                    response_serializer=TunableChanneld__pb2.GetCenterFrequencyReply.SerializeToString,
            ),
            'SetCenterFrequency': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCenterFrequency,
                    request_deserializer=TunableChanneld__pb2.SetCenterFrequencyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetAnalogBandwidth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalogBandwidth,
                    request_deserializer=TunableChanneld__pb2.GetAnalogBandwidthRequest.FromString,
                    response_serializer=TunableChanneld__pb2.GetAnalogBandwidthReply.SerializeToString,
            ),
            'SetAnalogBandwidth': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAnalogBandwidth,
                    request_deserializer=TunableChanneld__pb2.SetAnalogBandwidthRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetSampleRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSampleRate,
                    request_deserializer=TunableChanneld__pb2.GetSampleRateRequest.FromString,
                    response_serializer=TunableChanneld__pb2.GetSampleRateReply.SerializeToString,
            ),
            'SetSampleRate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSampleRate,
                    request_deserializer=TunableChanneld__pb2.SetSampleRateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetHardwareGain': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHardwareGain,
                    request_deserializer=TunableChanneld__pb2.GetHardwareGainRequest.FromString,
                    response_serializer=TunableChanneld__pb2.GetHardwareGainReply.SerializeToString,
            ),
            'SetHardwareGain': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHardwareGain,
                    request_deserializer=TunableChanneld__pb2.SetHardwareGainRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serosystems.proto.v3.grx.tunablechanneld.TunableChanneld', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TunableChanneld(object):
    """TunableChannel daemon service definition. Port 5309. 
    """

    @staticmethod
    def GetChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetChannels',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            TunableChanneld__pb2.GetChannelsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRXPorts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetRXPorts',
            TunableChanneld__pb2.GetRXPortsRequest.SerializeToString,
            TunableChanneld__pb2.GetRXPortsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRXPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetRXPort',
            TunableChanneld__pb2.GetRXPortRequest.SerializeToString,
            TunableChanneld__pb2.GetRXPortReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRXPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/SetRXPort',
            TunableChanneld__pb2.SetRXPortRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCenterFrequency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetCenterFrequency',
            TunableChanneld__pb2.GetCenterFrequencyRequest.SerializeToString,
            TunableChanneld__pb2.GetCenterFrequencyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCenterFrequency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/SetCenterFrequency',
            TunableChanneld__pb2.SetCenterFrequencyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAnalogBandwidth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetAnalogBandwidth',
            TunableChanneld__pb2.GetAnalogBandwidthRequest.SerializeToString,
            TunableChanneld__pb2.GetAnalogBandwidthReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAnalogBandwidth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/SetAnalogBandwidth',
            TunableChanneld__pb2.SetAnalogBandwidthRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSampleRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetSampleRate',
            TunableChanneld__pb2.GetSampleRateRequest.SerializeToString,
            TunableChanneld__pb2.GetSampleRateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSampleRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/SetSampleRate',
            TunableChanneld__pb2.SetSampleRateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHardwareGain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/GetHardwareGain',
            TunableChanneld__pb2.GetHardwareGainRequest.SerializeToString,
            TunableChanneld__pb2.GetHardwareGainReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetHardwareGain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serosystems.proto.v3.grx.tunablechanneld.TunableChanneld/SetHardwareGain',
            TunableChanneld__pb2.SetHardwareGainRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
